[package]
name = "ev-cmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
dirs = "5.0.1"
evdev = "0.12.2"
toml = "0.8.14"
